[2023-11-01T00:42:30.226+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates permission to 509
[2023-11-01T00:42:30.228+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates'
[2023-11-01T00:42:30.281+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates permission to 509
[2023-11-01T00:42:30.283+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates'
[2023-11-01T00:42:30.336+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: col_api_etl.extract_currency_conversion_rates manual__2023-11-01T00:42:24.624685+00:00 [queued]>
[2023-11-01T00:42:30.347+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: col_api_etl.extract_currency_conversion_rates manual__2023-11-01T00:42:24.624685+00:00 [queued]>
[2023-11-01T00:42:30.348+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-01T00:42:30.368+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_currency_conversion_rates> on 2023-11-01 00:42:24.624685+00:00
[2023-11-01T00:42:30.374+0000] {standard_task_runner.py:57} INFO - Started process 15732 to run task
[2023-11-01T00:42:30.375+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-11-01T00:42:30.380+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'col_api_etl', 'extract_currency_conversion_rates', 'manual__2023-11-01T00:42:24.624685+00:00', '--job-id', '1151', '--raw', '--subdir', 'DAGS_FOLDER/col_api_etl.py', '--cfg-path', '/tmp/tmpbbrmqg5j']
[2023-11-01T00:42:30.382+0000] {standard_task_runner.py:85} INFO - Job 1151: Subtask extract_currency_conversion_rates
[2023-11-01T00:42:30.443+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-11-01T00:42:30.445+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-11-01T00:42:30.446+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates permission to 509
[2023-11-01T00:42:30.447+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-01T00:42:24.624685+00:00/task_id=extract_currency_conversion_rates'
[2023-11-01T00:42:30.446+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-11-01T00:42:30.450+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-11-01T00:42:30.451+0000] {task_command.py:415} INFO - Running <TaskInstance: col_api_etl.extract_currency_conversion_rates manual__2023-11-01T00:42:24.624685+00:00 [running]> on host 65ec58942685
[2023-11-01T00:42:30.737+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='col_api_etl' AIRFLOW_CTX_TASK_ID='extract_currency_conversion_rates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:42:24.624685+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-01T00:42:24.624685+00:00'
[2023-11-01T00:42:33.670+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-01T00:42:33.688+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=col_api_etl, task_id=extract_currency_conversion_rates, execution_date=20231101T004224, start_date=20231101T004230, end_date=20231101T004233
[2023-11-01T00:42:33.735+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
