[2023-10-29T02:45:33.114+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city permission to 509
[2023-10-29T02:45:33.115+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city'
[2023-10-29T02:45:33.149+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city permission to 509
[2023-10-29T02:45:33.151+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city'
[2023-10-29T02:45:33.181+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: col_api_etl.extract_numbeo_prices_from_city manual__2023-10-29T02:40:10.670472+00:00 [queued]>
[2023-10-29T02:45:33.190+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: col_api_etl.extract_numbeo_prices_from_city manual__2023-10-29T02:40:10.670472+00:00 [queued]>
[2023-10-29T02:45:33.191+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-29T02:45:33.202+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_numbeo_prices_from_city> on 2023-10-29 02:40:10.670472+00:00
[2023-10-29T02:45:33.207+0000] {standard_task_runner.py:57} INFO - Started process 35095 to run task
[2023-10-29T02:45:33.207+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-29T02:45:33.210+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'col_api_etl', 'extract_numbeo_prices_from_city', 'manual__2023-10-29T02:40:10.670472+00:00', '--job-id', '1105', '--raw', '--subdir', 'DAGS_FOLDER/col_api_etl.py', '--cfg-path', '/tmp/tmp023xqzim']
[2023-10-29T02:45:33.212+0000] {standard_task_runner.py:85} INFO - Job 1105: Subtask extract_numbeo_prices_from_city
[2023-10-29T02:45:33.250+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city permission to 509
[2023-10-29T02:45:33.250+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:40:10.670472+00:00/task_id=extract_numbeo_prices_from_city'
[2023-10-29T02:45:33.252+0000] {task_command.py:415} INFO - Running <TaskInstance: col_api_etl.extract_numbeo_prices_from_city manual__2023-10-29T02:40:10.670472+00:00 [running]> on host ea85de3a6109
[2023-10-29T02:45:33.320+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='col_api_etl' AIRFLOW_CTX_TASK_ID='extract_numbeo_prices_from_city' AIRFLOW_CTX_EXECUTION_DATE='2023-10-29T02:40:10.670472+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-29T02:40:10.670472+00:00'
[2023-10-29T02:45:33.973+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-10-29T02:45:33.974+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-29T02:45:33.975+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-10-29T02:45:33.978+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-29T02:45:34.808+0000] {logging_mixin.py:151} INFO - Dubai
[2023-10-29T02:45:40.645+0000] {logging_mixin.py:151} INFO - Abu-Dhabi
[2023-10-29T02:45:46.219+0000] {logging_mixin.py:151} INFO - Sharjah
[2023-10-29T02:45:51.516+0000] {logging_mixin.py:151} INFO - Perth
[2023-10-29T02:45:57.166+0000] {logging_mixin.py:151} INFO - Melbourne
[2023-10-29T02:46:02.709+0000] {logging_mixin.py:151} INFO - Sydney
[2023-10-29T02:46:08.342+0000] {logging_mixin.py:151} INFO - Brisbane
[2023-10-29T02:46:14.194+0000] {logging_mixin.py:151} INFO - Hobart
[2023-10-29T02:46:19.423+0000] {logging_mixin.py:151} INFO - Adelaide
[2023-10-29T02:46:24.961+0000] {logging_mixin.py:151} INFO - Canberra
[2023-10-29T02:46:30.388+0000] {logging_mixin.py:151} INFO - Darwin
[2023-10-29T02:46:35.665+0000] {logging_mixin.py:151} INFO - Sarajevo
[2023-10-29T02:46:41.192+0000] {logging_mixin.py:151} INFO - Manama
[2023-10-29T02:46:46.717+0000] {logging_mixin.py:151} INFO - Sofia
[2023-10-29T02:46:52.531+0000] {logging_mixin.py:151} INFO - Sao-Paulo
[2023-10-29T02:46:58.204+0000] {logging_mixin.py:151} INFO - Rio-De-Janeiro
[2023-10-29T02:47:03.723+0000] {logging_mixin.py:151} INFO - Brasilia
[2023-10-29T02:47:09.857+0000] {logging_mixin.py:151} INFO - Toronto
[2023-10-29T02:47:15.701+0000] {logging_mixin.py:151} INFO - Montreal
[2023-10-29T02:47:21.501+0000] {logging_mixin.py:151} INFO - Vancouver
[2023-10-29T02:47:26.994+0000] {logging_mixin.py:151} INFO - Ottawa
[2023-10-29T02:47:33.084+0000] {logging_mixin.py:151} INFO - Calgary
[2023-10-29T02:47:38.599+0000] {logging_mixin.py:151} INFO - Edmonton
[2023-10-29T02:47:44.300+0000] {logging_mixin.py:151} INFO - Halifax
[2023-10-29T02:47:49.849+0000] {logging_mixin.py:151} INFO - Quebec-City
[2023-10-29T02:47:55.416+0000] {logging_mixin.py:151} INFO - Zurich
[2023-10-29T02:48:01.417+0000] {logging_mixin.py:151} INFO - Geneva
[2023-10-29T02:48:06.661+0000] {logging_mixin.py:151} INFO - Zug
[2023-10-29T02:48:11.895+0000] {logging_mixin.py:151} INFO - Basel
[2023-10-29T02:48:17.409+0000] {logging_mixin.py:151} INFO - Bern
[2023-10-29T02:48:22.646+0000] {logging_mixin.py:151} INFO - Lausanne
[2023-10-29T02:48:28.468+0000] {logging_mixin.py:151} INFO - Lugano
[2023-10-29T02:48:34.536+0000] {logging_mixin.py:151} INFO - Vaduz
[2023-10-29T02:48:39.762+0000] {logging_mixin.py:151} INFO - Santiago
[2023-10-29T02:48:45.303+0000] {logging_mixin.py:151} INFO - Chongqing
[2023-10-29T02:48:50.566+0000] {logging_mixin.py:151} INFO - Shanghai
[2023-10-29T02:48:56.132+0000] {logging_mixin.py:151} INFO - Beijing
[2023-10-29T02:49:02.020+0000] {logging_mixin.py:151} INFO - Chengdu
[2023-10-29T02:49:07.283+0000] {logging_mixin.py:151} INFO - Guangzhou
[2023-10-29T02:49:12.550+0000] {logging_mixin.py:151} INFO - Shenzhen
[2023-10-29T02:49:18.060+0000] {logging_mixin.py:151} INFO - Bogota
[2023-10-29T02:49:23.734+0000] {logging_mixin.py:151} INFO - Medellin
[2023-10-29T02:49:29.574+0000] {logging_mixin.py:151} INFO - Cali
[2023-10-29T02:49:35.080+0000] {logging_mixin.py:151} INFO - Cartagena
[2023-10-29T02:49:40.325+0000] {logging_mixin.py:151} INFO - San-Jose
[2023-10-29T02:49:45.564+0000] {logging_mixin.py:151} INFO - Prague
[2023-10-29T02:49:51.117+0000] {logging_mixin.py:151} INFO - Brno
[2023-10-29T02:49:56.632+0000] {logging_mixin.py:151} INFO - Ostrava
[2023-10-29T02:50:01.865+0000] {logging_mixin.py:151} INFO - Copenhagen
[2023-10-29T02:50:07.430+0000] {logging_mixin.py:151} INFO - Aarhus
[2023-10-29T02:50:12.610+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/extraction.py", line 141, in extract_numbeo_prices_from_city
    prices_table = numbeo_prices_city_html.find('table', {'class': 'data_wide_table new_bar_table'}).find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'
[2023-10-29T02:50:12.624+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=col_api_etl, task_id=extract_numbeo_prices_from_city, execution_date=20231029T024010, start_date=20231029T024533, end_date=20231029T025012
[2023-10-29T02:50:12.796+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1105 for task extract_numbeo_prices_from_city ('NoneType' object has no attribute 'find_all'; 35095)
[2023-10-29T02:50:12.834+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
