[2023-10-29T02:58:30.169+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city permission to 509
[2023-10-29T02:58:30.169+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city'
[2023-10-29T02:58:30.194+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city permission to 509
[2023-10-29T02:58:30.195+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city'
[2023-10-29T02:58:30.224+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: col_api_etl.extract_numbeo_prices_from_city manual__2023-10-29T02:58:18.529946+00:00 [queued]>
[2023-10-29T02:58:30.233+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: col_api_etl.extract_numbeo_prices_from_city manual__2023-10-29T02:58:18.529946+00:00 [queued]>
[2023-10-29T02:58:30.234+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-29T02:58:30.245+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_numbeo_prices_from_city> on 2023-10-29 02:58:18.529946+00:00
[2023-10-29T02:58:30.250+0000] {standard_task_runner.py:57} INFO - Started process 39065 to run task
[2023-10-29T02:58:30.250+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-29T02:58:30.253+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'col_api_etl', 'extract_numbeo_prices_from_city', 'manual__2023-10-29T02:58:18.529946+00:00', '--job-id', '1107', '--raw', '--subdir', 'DAGS_FOLDER/col_api_etl.py', '--cfg-path', '/tmp/tmpspsu8qoj']
[2023-10-29T02:58:30.254+0000] {standard_task_runner.py:85} INFO - Job 1107: Subtask extract_numbeo_prices_from_city
[2023-10-29T02:58:30.291+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city permission to 509
[2023-10-29T02:58:30.292+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-10-29T02:58:18.529946+00:00/task_id=extract_numbeo_prices_from_city'
[2023-10-29T02:58:30.294+0000] {task_command.py:415} INFO - Running <TaskInstance: col_api_etl.extract_numbeo_prices_from_city manual__2023-10-29T02:58:18.529946+00:00 [running]> on host ea85de3a6109
[2023-10-29T02:58:30.362+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='col_api_etl' AIRFLOW_CTX_TASK_ID='extract_numbeo_prices_from_city' AIRFLOW_CTX_EXECUTION_DATE='2023-10-29T02:58:18.529946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-29T02:58:18.529946+00:00'
[2023-10-29T02:58:31.034+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-10-29T02:58:31.036+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-29T02:58:31.036+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-10-29T02:58:31.039+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-10-29T02:58:31.784+0000] {logging_mixin.py:151} INFO - Dubai
[2023-10-29T02:58:37.361+0000] {logging_mixin.py:151} INFO - Abu-Dhabi
[2023-10-29T02:58:42.936+0000] {logging_mixin.py:151} INFO - Sharjah
[2023-10-29T02:58:48.177+0000] {logging_mixin.py:151} INFO - Perth
[2023-10-29T02:58:53.694+0000] {logging_mixin.py:151} INFO - Melbourne
[2023-10-29T02:58:59.234+0000] {logging_mixin.py:151} INFO - Sydney
[2023-10-29T02:59:04.872+0000] {logging_mixin.py:151} INFO - Brisbane
[2023-10-29T02:59:10.390+0000] {logging_mixin.py:151} INFO - Hobart
[2023-10-29T02:59:15.627+0000] {logging_mixin.py:151} INFO - Adelaide
[2023-10-29T02:59:21.147+0000] {logging_mixin.py:151} INFO - Canberra
[2023-10-29T02:59:26.438+0000] {logging_mixin.py:151} INFO - Darwin
[2023-10-29T02:59:31.798+0000] {logging_mixin.py:151} INFO - Sarajevo
[2023-10-29T02:59:37.301+0000] {logging_mixin.py:151} INFO - Manama
[2023-10-29T02:59:42.634+0000] {logging_mixin.py:151} INFO - Sofia
[2023-10-29T02:59:48.507+0000] {logging_mixin.py:151} INFO - Sao-Paulo
[2023-10-29T02:59:54.359+0000] {logging_mixin.py:151} INFO - Rio-De-Janeiro
[2023-10-29T02:59:59.904+0000] {logging_mixin.py:151} INFO - Brasilia
[2023-10-29T03:00:05.435+0000] {logging_mixin.py:151} INFO - Toronto
[2023-10-29T03:00:11.309+0000] {logging_mixin.py:151} INFO - Montreal
[2023-10-29T03:00:17.091+0000] {logging_mixin.py:151} INFO - Vancouver
[2023-10-29T03:00:22.788+0000] {logging_mixin.py:151} INFO - Ottawa
[2023-10-29T03:00:28.420+0000] {logging_mixin.py:151} INFO - Calgary
[2023-10-29T03:00:34.005+0000] {logging_mixin.py:151} INFO - Edmonton
[2023-10-29T03:00:39.913+0000] {logging_mixin.py:151} INFO - Halifax
[2023-10-29T03:00:45.464+0000] {logging_mixin.py:151} INFO - Quebec-City
[2023-10-29T03:00:51.052+0000] {logging_mixin.py:151} INFO - Zurich
[2023-10-29T03:00:56.574+0000] {logging_mixin.py:151} INFO - Geneva
[2023-10-29T03:01:02.083+0000] {logging_mixin.py:151} INFO - Zug
[2023-10-29T03:01:07.346+0000] {logging_mixin.py:151} INFO - Basel
[2023-10-29T03:01:12.896+0000] {logging_mixin.py:151} INFO - Bern
[2023-10-29T03:01:18.385+0000] {logging_mixin.py:151} INFO - Lausanne
[2023-10-29T03:01:23.722+0000] {logging_mixin.py:151} INFO - Lugano
[2023-10-29T03:01:29.199+0000] {logging_mixin.py:151} INFO - Vaduz
[2023-10-29T03:01:34.530+0000] {logging_mixin.py:151} INFO - Santiago
[2023-10-29T03:01:40.057+0000] {logging_mixin.py:151} INFO - Chongqing
[2023-10-29T03:01:45.290+0000] {logging_mixin.py:151} INFO - Shanghai
[2023-10-29T03:01:50.835+0000] {logging_mixin.py:151} INFO - Beijing
[2023-10-29T03:01:56.758+0000] {logging_mixin.py:151} INFO - Chengdu
[2023-10-29T03:02:02.125+0000] {logging_mixin.py:151} INFO - Guangzhou
[2023-10-29T03:02:07.685+0000] {logging_mixin.py:151} INFO - Shenzhen
[2023-10-29T03:02:13.288+0000] {logging_mixin.py:151} INFO - Bogota
[2023-10-29T03:02:18.952+0000] {logging_mixin.py:151} INFO - Medellin
[2023-10-29T03:02:24.479+0000] {logging_mixin.py:151} INFO - Cali
[2023-10-29T03:02:30.186+0000] {logging_mixin.py:151} INFO - Cartagena
[2023-10-29T03:02:35.546+0000] {logging_mixin.py:151} INFO - San-Jose
[2023-10-29T03:02:40.810+0000] {logging_mixin.py:151} INFO - Prague
[2023-10-29T03:02:46.684+0000] {logging_mixin.py:151} INFO - Brno
[2023-10-29T03:02:52.307+0000] {logging_mixin.py:151} INFO - Ostrava
[2023-10-29T03:02:57.832+0000] {logging_mixin.py:151} INFO - Copenhagen
[2023-10-29T03:03:03.540+0000] {logging_mixin.py:151} INFO - Aarhus
[2023-10-29T03:03:09.039+0000] {logging_mixin.py:151} INFO - Aalborg
[2023-10-29T03:03:14.625+0000] {logging_mixin.py:151} INFO - Andorra-La-Vella
[2023-10-29T03:03:19.973+0000] {logging_mixin.py:151} INFO - Vienna
[2023-10-29T03:03:25.555+0000] {logging_mixin.py:151} INFO - Salzburg
[2023-10-29T03:03:31.287+0000] {logging_mixin.py:151} INFO - Graz
[2023-10-29T03:03:36.801+0000] {logging_mixin.py:151} INFO - Linz
[2023-10-29T03:03:42.170+0000] {logging_mixin.py:151} INFO - Innsbruck
[2023-10-29T03:03:47.401+0000] {logging_mixin.py:151} INFO - Brussels
[2023-10-29T03:03:52.963+0000] {logging_mixin.py:151} INFO - Antwerp
[2023-10-29T03:03:58.459+0000] {logging_mixin.py:151} INFO - Ghent
[2023-10-29T03:04:03.835+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/extraction.py", line 144, in extract_numbeo_prices_from_city
    prices_table = numbeo_prices_city_html.find('table', {'class': 'data_wide_table new_bar_table'}).find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'
[2023-10-29T03:04:03.850+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=col_api_etl, task_id=extract_numbeo_prices_from_city, execution_date=20231029T025818, start_date=20231029T025830, end_date=20231029T030403
[2023-10-29T03:04:03.865+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1107 for task extract_numbeo_prices_from_city ('NoneType' object has no attribute 'find_all'; 39065)
[2023-10-29T03:04:03.909+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
