[2023-12-02T01:11:30.634+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: col_api_etl.merge_and_transform_childcare manual__2023-12-02T00:54:25.961983+00:00 [queued]>
[2023-12-02T01:11:30.645+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: col_api_etl.merge_and_transform_childcare manual__2023-12-02T00:54:25.961983+00:00 [queued]>
[2023-12-02T01:11:30.646+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-02T01:11:30.661+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): merge_and_transform_childcare> on 2023-12-02 00:54:25.961983+00:00
[2023-12-02T01:11:30.669+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-12-02T01:11:30.669+0000] {standard_task_runner.py:57} INFO - Started process 7883 to run task
[2023-12-02T01:11:30.673+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'col_api_etl', 'merge_and_transform_childcare', 'manual__2023-12-02T00:54:25.961983+00:00', '--job-id', '1336', '--raw', '--subdir', 'DAGS_FOLDER/col_api_etl.py', '--cfg-path', '/tmp/tmpsq5l953r']
[2023-12-02T01:11:30.675+0000] {standard_task_runner.py:85} INFO - Job 1336: Subtask merge_and_transform_childcare
[2023-12-02T01:11:30.726+0000] {task_command.py:415} INFO - Running <TaskInstance: col_api_etl.merge_and_transform_childcare manual__2023-12-02T00:54:25.961983+00:00 [running]> on host dbead8e210dd
[2023-12-02T01:11:30.827+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='col_api_etl' AIRFLOW_CTX_TASK_ID='merge_and_transform_childcare' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T00:54:25.961983+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T00:54:25.961983+00:00'
[2023-12-02T01:11:31.270+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-12-02T01:11:31.271+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-12-02T01:11:31.272+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-12-02T01:11:31.275+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-12-02T01:11:46.063+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-02T01:11:46.075+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=col_api_etl, task_id=merge_and_transform_childcare, execution_date=20231202T005425, start_date=20231202T011130, end_date=20231202T011146
[2023-12-02T01:11:46.110+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
